### ISSUE TITLE
blacklist.txt has domains prepended with dot

### ISSUE THREAD

**Issue by scarver2** [willwhite/freemail#3]
The blacklist file is in a different format than the freemail.txt and disposable.txt files. I don't think it should not have the "period" in the domain name for consistency.

**Comment by willwhite** [comment]
blacklist.txt lists domains that don't want in the final database, so it's likely to look messy and inconsistent. The leading period is how those domain are represented in [upstream sources](https://github.com/willwhite/freemail/blob/master/data/sources.txt), so the blacklist also includes it to make sure they are scrubbed.
